### Get All Cars
GET http://localhost:8085/cars

### Find Car By Id
GET http://localhost:8085/cars/3

### Add New Car
POST http://localhost:8085/save
Content-Type: application/json

{
  "name" : "name",
  "model" : "",
  "color" : "black",
  "year" : 2005,
  "customerName" : "",
  "rentEndDate" : ""
}

### Rent a Car
PATCH http://localhost:8085/cars/rent
Content-Type: application/json

{
  "id" : 2,
  "name" : "",
  "model" : "",
  "color" : "black",
  "year" : 2005,
  "customerName" : "yaqout",
  "rentEndDate" : "2023-04-12"
}