### Get All Cars
GET http://localhost:8085/cars

### Find Car By Id
GET http://localhost:8085/cars/4

### Add New Car
POST http://localhost:8085/cars/save
Content-Type: application/json

{
  "id" : 22,
  "name" : "name",
  "model" : "",
  "color" : "black",
  "year" : 2005,
  "customerName" : "",
  "rentEndDate" : ""
}

### Rent a Car
PATCH http://localhost:8085/cars/rent
Content-Type: application/json

{
  "id" : 802,
  "name" : "",
  "model" : "",
  "color" : "black",
  "year" : 2005,
  "customerName" : "yaqout",
  "rentEndDate" : "2023-10-29"
}

### Delete a Car
DELETE http://localhost:8085/cars/553


## Notifications ##

### Get all notifications
GET http://localhost:8085/notifications

### Delete a notification
DELETE http://localhost:8085/notifications/tfF7t4kBNmbJDprjq9Or