### Find All Cars
GET http://localhost:8085/cars

### Get Car By Id
GET http://localhost:8085/cars/4

### Add New Car
POST http://localhost:8085/save
Content-Type: application/json

{
  "name" : "name",
  "model" : "",
  "color" : "black",
  "year" : 2005,
  "customerName" : "Sara",
  "rentEndDate" : "2023-04-10"
}